# Generated by Django 2.1.3 on 2018-11-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumbers',
            new_name='PhoneNumber',
        ),
    ]
