# Generated by Django 2.1.3 on 2018-11-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0002_auto_20181123_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('day_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='call_stats.PhoneNumber'),
        ),
        migrations.AlterField(
            model_name='callinfo',
            name='phone_dialed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='call_stats.PhoneNumber'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='days',
            field=models.ManyToManyField(to='call_stats.WeekDay'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='call_stats.RepeatPeriod'),
        ),
    ]
