# Generated by Django 2.1.3 on 2018-11-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0003_auto_20181123_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
