# Generated by Django 2.1.3 on 2018-11-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0006_periodictask_priority'),
        ('call_stats', '0004_schedule_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryPhoneModel',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=14, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
