# Generated by Django 2.1.3 on 2018-11-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0005_celeryphonemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinfo',
            name='phone_dialed',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='days',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='period',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='CallInfo',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='RepeatPeriod',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
