# Generated by Django 2.1.3 on 2018-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0007_callstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celeryphonemodel',
            name='title',
        ),
        migrations.AddField(
            model_name='celeryphonemodel',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
