# Generated by Django 2.1.3 on 2018-11-30 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('call_stats', '0009_auto_20181130_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwilioSettings',
            new_name='TwilioSetting',
        ),
    ]
