# Generated by Django 2.1.3 on 2018-12-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0010_auto_20181130_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliosetting',
            name='call_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
