# Generated by Django 2.1.3 on 2018-12-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0012_auto_20181204_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twiliosetting',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='callstat',
            name='debug_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
