# Generated by Django 2.1.3 on 2018-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_stats', '0014_auto_20181211_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliosetting',
            name='test_phone_number',
            field=models.CharField(blank=True, default='15005550006', max_length=255, null=True),
        ),
    ]
